<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>GhostlingDotNet</RootNamespace>
    <AssemblyName>GhostlingDotNet</AssemblyName>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Ghostty.Vt\Ghostty.Vt.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Raylib-cs" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="fonts\JetBrainsMonoNerdFont-Regular.ttf" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="..\..\runtimes\win-x64\native\libghostty-vt.dll"
          Link="ghostty-vt.dll"
          CopyToOutputDirectory="PreserveNewest"
          Condition="Exists('..\..\runtimes\win-x64\native\libghostty-vt.dll')" />
  </ItemGroup>
</Project>
